### ISSUE TITLE
Source is added twice for membership contributions

### ISSUE THREAD

**Issue by larssandergreen** [twomice/com.joineryhq.referralsource#2]
Love this extension, very useful!

I'm finding that membership contributions are appending to the source twice (e.g. Online Contribution: Page - foo - foo), but not any other contributions. Verified this on multiple contribution pages.

5.28.4 on Drupal.

**Comment by lucky091588** [comment]
@larssg-wildsight Thanks for reporting this. I am trying to replicate the issue right now using the same CiviCRM version in Drupal7 so that I can fix it but failed.

Can you tell me more details about the membership contributions setting? Title, Amounts and Membership settings to be precise?

**Comment by larssandergreen** [comment]
@lucky091588 Thanks!

We have "Join Our Community" as the title, no amounts enabled on the contribution page, with a few membership options:

![image](https://user-images.githubusercontent.com/25517556/98180616-aa04e880-1ebe-11eb-915a-578bdb944e34.png)

These are the membership types:

![image](https://user-images.githubusercontent.com/25517556/98180678-d15bb580-1ebe-11eb-8c7e-9fc2f9f1c280.png)

They are all the same, just with different names and financial types associated. There is a profile with address, etc. included and no email receipt is sent.

If you'd like me to try a test membership contribution page with the settings you're using, I'm happy to do that. I did set up a test contribution page with very basic settings and had the same result.

**Comment by twomice** [comment]
@larssg-wildsight What version of Drupal is this?

**Comment by larssandergreen** [comment]
@twomice 7.73

**Comment by twomice** [comment]
Hi @larssg-wildsight We're finding that this does not happen when referralsource is the only extension enabled, and we suspect the problem may only appear in conjunction with one or more other specific extensions. Can you post here a list of your currently enabled extensions?

**Comment by larssandergreen** [comment]
@twomice Thanks so much for looking into this. I'd be happy to disable some of these that are contribution related and test (maybe Edit Line Item Extension, Move Contribution, Recurring Contributions to start and then IATS Payments and CDN Tax Receipts if those don't help).

We have:

Activity Status
(activitystatus)	Enabled	1.0	Module	
Advanced Log Tables
(at.greenpeace.advancedlogtables)	Enabled	1.0-beta.1	Module	
Edit Line Item Extension
(biz.jmaconsulting.lineitemedit)	Enabled	2.3	Module	
Move Contribution
(biz.lcdservices.movecontrib)	Enabled	2.0	Module	
Recurring Contributions
(ca.civicrm.contributionrecur)	Enabled	1.0	Module	
CiviCRM Log Viewer
(ca.civicrm.logviewer)	Enabled	1.2	Module	
Wildsight Branches
(ca.wildsight.branchregex)	Enabled	1.0	Module	
Group Joined Email Alert
(ca.wildsight.groupemailalert)	Enabled	1.0	Module	
Mosaico Toolbar Configurator
(com.ginkgostreet.mosaicotoolbarconfig)	Enabled	1.0	Module	
iATS Payments
(com.iatspayments.civicrm) Enabled	1.7.2	Module	
Referral Source
(com.joineryhq.referralsource)	Enabled	1.0	Module	
Save time preparing newsletters: Fancy tokens for upcoming events, petitions, contribution pages, and forms
(com.pogstone.fancytokens)	Enabled	5.1	Module	
Prevent users from overwriting their record
(eu.tttp.noverwrite)	Enabled	1.24	Module	
Former Communication Data
(formercommunicationdata)	Enabled	1.1	Module	
Advanced Fundraising Reports
(net.ourpowerbase.report.advancedfundraising)	Enabled	1.0.5	Module	
Summary Fields
(net.ourpowerbase.sumfields)	Enabled	4.0.2	Module	
Fuzion Tokens
(nz.co.fuzion.civitoken)	Enabled	1.7	Module	
CSV GUI Import to api
(nz.co.fuzion.csvimport)	Enabled	1.5	Module	
ExtendedReport
(nz.co.fuzion.extendedreport)	Enabled	5.6	Module	
CiviRules
(org.civicoop.civirules)	Enabled	2.19	Module	
E-mail API
(org.civicoop.emailapi)	Enabled	1.19	Module	
Angular Profiles
(org.civicrm.angularprofiles)	Enabled	4.7.31-1.1.2	Module	
CDN Tax Receipts
(org.civicrm.cdntaxreceipts) Enabled	1.5.1	Module	
FlexMailer
(org.civicrm.flexmailer)	Enabled	1.1.1	Module	
CiviCRM Bootstrap theme
(org.civicrm.shoreditch)	Enabled	1.0.0-beta.2	Module	
CiviVolunteer
(org.civicrm.volunteer)	Enabled	4.7.31-2.3.1	Module	
Contact Editor
(org.wikimedia.contacteditor)	Enabled	2.2	Module	
Resend Mailing
(resendmailing)	Enabled	1.0.1	Module	
Mosaico
(uk.co.vedaconsulting.mosaico)	Enabled	2.5	Module

**Comment by twomice** [comment]
Hi @larssg-wildsight Yes, if you're able to temporarily disable some or all of these, and then selectively re-enable one or a few at a time, you may be able to tell us which one(s) must be enabled to cause this behavior. We'll wait on your response.

**Comment by larssandergreen** [comment]
@twomice I've tried disabling everything on the list that I can think would possibly be related (the five I mentioned above, plus the two custom extensions we have, Contact Editor, Prevent users from overwriting their record). What I have noticed is that this only happens with a payment processor and not with pay later, so I just wanted to check if you are testing with a payment processor or with pay later before I keep disabling other extensions to test.

**Comment by twomice** [comment]
We tested with pay later @larssg-wildsight

**Comment by larssandergreen** [comment]
@twomice OK, can you try with a payment processor? This doesn't happen on my end using pay later either, so maybe it isn't related to another extension.

**Comment by twomice** [comment]
@larssg-wildsight Yes, we'll try that. Also, I'd like to know the short list of extensions that were still enabled after you disabled some. Is it correct to guess that this consists of the list of extensions in [your comment above](https://github.com/twomice/com.joineryhq.referralsource/issues/2#issuecomment-724930716), minus _biz.jmaconsulting.lineitemedit_, _biz.lcdservices.movecontrib_, _ca.civicrm.contributionrecur_, _com.iatspayments.civicrm_, _org.civicrm.cdntaxreceipts_, _ca.wildsight.branchregex_, _ca.wildsight.groupemailalert_, _org.wikimedia.contacteditor_, and _eu.tttp.noverwrite_ ? Did I miss any that you disabled in your testing?

**Comment by larssandergreen** [comment]
@twomice Yes, that's right. I have not tried with all of those disabled at the same time though (live site, so disabling com.iatspayments.civicrm stops processing of credit cards and I only want to do that very briefly).

Happy to keep testing by disabling other extensions, but just wanted to check if you're seeing the same as me with a payment processor versus pay later before I continue with that.

**Comment by twomice** [comment]
Thanks @larssg-wildsight We'll try to make time (amidst our existing client work) to repro this by enabling those extensions; if you happen to have time to narrow the list further, please post your results here.

**Comment by larssandergreen** [comment]
@twomice Thanks. I have tried disabling all the extensions and can say that nothing changed. Still the same result: doubled source with a payment processor, single source with pay later.

**Comment by twomice** [comment]
Thanks for the report @larssg-wildsight That is odd, but we'll try a few things here and see what we can do.

**Comment by twomice** [comment]
@larssandergreen Thanks for your help narrowing this down. I believe the latest commit (from PR #3 ) will fix this. Could you  please try the latest master branch and report back your findings on whether it does or doesn't fix the issue for you?

**Comment by larssandergreen** [comment]
Works for me. Thanks for tracking this down!

**Comment by twomice** [comment]
Fantastic, thanks @larssandergreen for confirming and @lucky091588 for the fix. Closing.

**Comment by twomice** [comment]
Released in v1.1
