### ISSUE TITLE
Not working for Civi 5.38.2

### ISSUE THREAD

**Issue by tapashdatta** [twomice/com.joineryhq.referralsource#4]
I have never tried this extension before. I am currently on Civicrm 5.38.x. Stripe 6.6.1, I was not able to get it work.
https://test.london/civicrm/contribute/transact?id=1&source=referraltest this was my test url, did not see any error in the log but nothing added to source field.

Tried with a checksum link also, but no luck.

**Comment by twomice** [comment]
Thanks for the report @tapashdatta. At this point, I'm seeing this as "works for me" , under these versions:

*  civicrm 5.40.3
* referralsource 1.1.1
* stripe 6.6.1
* Drupal 7.82
 
If, as you say, it's not working for you, I can suggest these things:

1. Upgrade to a current security release of civicrm (>= 5.40.2 or >= 5.39.2 ESR); it's hard for us to guarantee functionality under civicrm core versions older than a current security release.
2. Disable all other extensions.

If you find it's still not working for you, I'd love to help if you can provide these things:

1. A list of the versions you're using for the packages I mention above (and if not Drupal, then WP/Backdrop/etc.)
2. Specific steps you're taking to create the bad behavior.
3. Screenshots of 
  1. your contribution page config
  2. browser including address bar for live contribution page, confirmation page (if used), and thank-you page
  3. the resulting contribution record in civicrm back-office area.

Thanks. Looking forward to your response.

**Comment by twomice** [comment]
Marking as "invalid" -- not the label I'd like to use, but the best one available on this project. Basically, this means "I can't yet act on this issue" , pending more input from the OP.

**Comment by tapashdatta** [comment]
Hi Allen
Thanks for your reply. It seems a custom extension on my site has Caused the conflict.

**Comment by twomice** [comment]
I'm glad you found that, Tapash, and thanks for letting us know.
